### ISSUE TITLE
Dear companies, it needs money to make money!

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-bacnet#14]
A warm welcome to all companies that sell or offer our Open Source software! Very few or to say only a few companies give a small contribution to the projects to maintain and develop this software. Node.js and your security in the projects require a continuous development of the Node-RED contribution projects. Unfortunately we are only facing demands and no support. We have been observing this behavior for more than four years now. We want to leave a small statement about this: Please give us a little support via sponsoring, because many small supports will give us enough strength in the end to continue see https://osi.bianco-royal.com/

Buy me a ☕️  is here to find on [PayPal](https://paypal.me/BiancoRoyal/) or use GitHub sponsoring, please!

**Comment by industrialinternet** [comment]
Hi Klaus have you considered Patron to support smaller amounts especially from the Node-RED community? Many of us would like to support you but don't need one month/yr support.
Again thanks for all your good work.

**Comment by biancode** [comment]
@industrialinternet thank you for the hint. We tested this over the last two years and it brought 0.00 :) - response was: "We do not know what we get for our money." - interesting - 
The OSI packages are the consequece of some talks about that.

Buy me a ☕️  is here to find on [PayPal](https://paypal.me/BiancoRoyal/) ...

**Comment by biancode** [comment]
@industrialinternet thank you very much for the ☕️  👍

**Comment by industrialinternet** [comment]
Your welcome have you heard of this group it's what the Aedes MQTT group use to support them. 
https://docs.opencollective.com/help/
