### ISSUE TITLE
BACnet write priority settings missing

### ISSUE THREAD

**Issue by Ekristoffe** [BiancoRoyal/node-red-contrib-bacnet#15]
Hello,
I was playing with this node and saw there is no option to set the priority yet.
Do you ave any plan to enable it in the future or could I make the modification and do a Pull request ?
Thanks.

Ps I am just playing with a rpi as slave (modbus, BACnet, mqtt, ...) and a windows pc (node-red) at  home.

**Comment by biancode** [comment]
v0.2.3 released - @Ekristoffe please test it

**Comment by Ekristoffe** [comment]
thanks

**Comment by Ekristoffe** [comment]
The change work fine but I think it could be better.
I will made some minor change:
Put in the textbox the default value grayed.
Change the default value to 16 (Lowest priority available)
Is there other changes needed ?

**Comment by biancode** [comment]
v0.2.4 released - @Ekristoffe please test it

**Comment by biancode** [comment]
@Ekristoffe you're right codacy lost the eslint settings again ... I'll fix that in the next few days to get it checked with single quotes, no semis and standardjs linting ;)

**Comment by Ekristoffe** [comment]
@biancode I saw on the codacy pages we can include a ESLint configuration file in the repository root to have those settings set.

Ps v0.2.4 work fine thanks.
