### ISSUE TITLE
feature: cov-bacnet node for monitoring values

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-bacnet#19]
## Feature
 - (X) feature request
 
 **What is the motivation / use case for changing the behavior?**
 
 
COV is supported by the node-bacnet library and could be implemented in the package as a cov-bacnet node.

**Comment by ice-web** [comment]
The use is that some Building Automation sequences cannot tolerate latency. For example we could use Node Red to collect button status from BACnet devices (COV read node) and then trigger BACnet relay(s) (write node) for lighting as an example. Maybe the user wants lighting relay A to come on if push buttons 1, 3 ,4 are pushed. Then relay C to come on if button 1 or 7 is pushed and it's dark outside and Joe is within his ge-o-fence. You get the idea. BACnet can push each button status on a different COV node so the flow will see the result as soon as it happens. 
Another use would be motion sensor monitoring over BACnet as a motion event could be missed by polling only.

I have been in commercial building automation systems for a long time and it's all about BACnet in this world. I'm new to Node Red and feel like "where have you been all these years?".. You are very close to having a extremely useful product for those of us in this industry.

**Comment by industrialinternet** [comment]
@ice-web Klaus does amazing work for Free!
Note this software is Not Ashrae approved.
I would like COV but think we will have to pay to get that.

**Comment by pmintegrator** [comment]
Hi everyone, I would really need some help reading in COV bacnet mode and avoid using the Read node by polling continuously.  Is the COV-Bacnet-Node available?  Thanks so much.

**Comment by biancode** [comment]
there is a lot of work and testing to do see https://github.com/BiancoRoyal/node-bacstack/issues
