### ISSUE TITLE
Is this supposed to work with Node Red v1.0.3?  I get a lot of errors or blank information using the sample flow.  Has something changed in the supporting code?

### ISSUE THREAD

**Issue by kskenyon** [BiancoRoyal/node-red-contrib-bacnet#20]
**I'm submitting a ...**  (check one with "x")

### Problem
 - ( ) bug report => please search github for a similar issue or PR before submitting
 - ( ) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
 
 
 **Expected behavior**
 
 
 **Minimal reproduction of the problem with instructions**
 
   1. 
   2. 
   3. 
   
 ## Feature
 - ( ) feature request
 
 **What is the motivation / use case for changing the behavior?**
 
 
 
 ## Support
 - support request => **Please do not submit support requests here**, instead see use [the link to our support page](https://bianco-royal.cloud/supporter/#/content/backer)
 - ( ) simple question => please visit the Wiki and Info tab by clicking on the node inside Node-RED before

## Your Environment
**Please tell us about your environment:**

  * ( ) I am using just the Node-RED package and got node-bacstack installed with it
  * ( ) I have installed node-bacstack global from source (using git clone)
  * ( ) I have installed node-bacstack as a global package (using npm i -g)
        
  * Device :
    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting BACnet system:
   
     - Name   :
     - Version:
     - Vendor :
     - Link   : https://
     
    
* **node-red-contrib-bacnet version:** ``

* **Node:** (min. 6.10.x)
   `node --version` =

**Comment by biancode** [comment]
Hi, it is not to answer with just the Node-RED version. It depends on more as we try to ask you with the template. Please, reopen if you have more information for us. The example flow is maybe not up to date as well.
