### ISSUE TITLE
BACnet write priority Relase

### ISSUE THREAD

**Issue by hminder** [BiancoRoyal/node-red-contrib-bacnet#23]
hello 
I found a little bug in the App-tag Setings. in fact, with the value "NULL", the number 0 is not entered in the field, its entering NULL. This means that the written array cannot be released again. It works if the number 0 is entered by hand. But it works for the rest of the entries.

I am using the following version:
1.3.5 Maintenance Release
node-red-contrib-bacnet 0.2.4 

AND 

BAcnet Server Simulator (BOSS Simulator Rev19)

Greetings from Switzerland Ruedi

and TX for the Work
![2021-06-05 15_03_02-Node-RED](https://user-images.githubusercontent.com/38588290/120892583-64a0c900-c60f-11eb-847c-81df90e5f673.png)
![2021-06-05 15_13_51-Node-RED](https://user-images.githubusercontent.com/38588290/120892906-b3029780-c610-11eb-80b6-5438530d3800.png)
![2021-06-05 15_13_18-Node-RED](https://user-images.githubusercontent.com/38588290/120892909-b3029780-c610-11eb-9ecf-bc49f71bd042.png)

**Comment by jli113** [comment]
It is the same in BACnet Read
