### ISSUE TITLE
Device ID Question

### ISSUE THREAD

**Issue by Wheelman1912** [BiancoRoyal/node-red-contrib-bacnet#24]
Dear Sir:

First let me start by saying that this is the first time I am ever trying to work with Node-Red at all. I am a Building Automation Control Guy with 20 years of experience working in the field and have been working with Bacnet in and out every day for the past 8 years as my primary language. 

What I am trying to do is I have a customer who has a very simplistic thermostat based system setup that currently is all stand-alone that was all installed by the previous building owners, so they inherited the system when they moved in. The system currently has no Building Management Device installed and so is completely stand-alone. The issue they are running into is when there is a power outage all of thermostats resort back to factory default date and wait for a time sync from the network...which never comes as there is no management device. So I am just needing a simple device to install to preform this task..thus I am looking into Node-red and your Pallet as a simple way to get that done. 

The issue that I am running into, and I probably just don't know what I'm doing, is that when you go to configure the Bacnet Command block with the Time Sync function you are asked for a device...which I don't see a way to define...an example is given of an IP address and this may work if all of your devices were straight Bacnet/IP devices but using straight IP addresses is not standard for Bacnet Transit Packets which is what leaves me confused, for like in my building system all of the devices are MSTP (RS-485 Network Based) devices. I can install a router to get from Bacnet/IP to the MSTP network but to send to each individual device I would need to identify each thermostat as its Bacnet ID on the Network, 1, 2, 3, 4, 5, etc. 

Can you please assist with this? Also, I see that you are looking for sponsorship and that your product is still in Beta. I would be willing to support you if you can support me.

Thank You,

Andy Burch
ab1912@hotmail.com

**Comment by biancode** [comment]
Hello Andy, I'm sorry, but it supports just Bacnet/IP for now. RS-485 or lets say serial is not implemented and MSTP needs much more work as Bacnet/IP. Maybe it is easier to use a library for C++ and implement it into Node-RED functions of you need MSTP.

**Comment by biancode** [comment]
We'll work on the package soon to improve it from you sponsoring.

**Comment by Wheelman1912** [comment]
Thank you for being willing to work on this and making improvements. If there is anything I can do to assist, any Bacnet related questions you may have, let me know and I'll see what I can do to assist. Just wondering, how's it going with the improvements so far?

Andy Burch

**Comment by biancode** [comment]
I'm sorry we had a lot Covid issues in the last weeks. Now it starts to get back to a more normal workflow to work on that.
