### ISSUE TITLE
It needs contributors! Get started with Gitpod!

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-bacnet#7]
[Introduction June-2020](https://www.loom.com/share/e98eaa86f16047a5aa8a8aa26f04a42e)

[Help to fix the code!](https://www.loom.com/share/3a63435ae14d4e218da4305a5aa61b61)

Are you familiar with BACnet and JavaScript? Great! 
**[Please, help that project named node-bacnet (npm name) to grow faster!](https://github.com/BiancoRoyal/node-bacstack/issues)**

**Comment by juniormercato** [comment]
I work as technical support in an automation company, I know a lot about BACnet, Bacnet over IP or MS / TP.
Currently I do not know much JAVAScript, but I am open to help in the development of the project.
In my house, I have automation with both the physical means of the protocol (Serial and IP). The Serial physical medium is being routed through a proprietary BACnet router. In the current version of the project, I only have IP layer access. To access the MS / TP layer, I need to define a network number or MS / TP MAC Address.
Sorry for the bad English, I'm Brazilian and I used Google Translate for this.

**Comment by biancode** [comment]
You are welcome!

**Comment by biancode** [comment]
For development and testing local local see the NPM scripts ;)
